---
layout: page
title: Research
permalink: /research/
---

## Publications

**Late-Adolescents Entering College Intending a Career As Police Officers Hold More Right-Leaning Views Than Their Peers (with Tyler Reny, Benjamin Newman, and David Sears)** Forthcoming, *Proceedings of the National Academy of Sciences*

**Self-Interest and Voter Support for Defund the Police (first author, with Benjamin Newman)** *Electoral Studies* (2025) [[PDF]](pdfs/pubs/dtp_fin.pdf)  [[Replication]](https://www.dropbox.com/scl/fo/4ncs5v9h4jzp0jdo61mon/AE8qMsary3gnSLiR2sQYRh4?rlkey=7udwp19n4dlzecic0j6mpbjgf&st=onhxg6il&dl=0
) 

**White Power! How White Status Threat Undercuts Backlash Against Anti-democratic Politicians (with Kiara Hernandez and Taeku Lee)** *Journal of Race, Ethnicity, and Politics* (2025) [[PDF]](pdfs/pubs/j6_fin.pdf)

**Policing Socio-Demographic Boundaries and Inequality (with Allison Verrilli, Hannah Walker, Derek Epp, Amy Liu, and Mike Findley)** *Perspectives on Politics* (2025) [[PDF]](pdfs/pubs/boundaries_fin.pdf) [[Replication]](https://doi.org/10.7910/DVN/LLRHWU)

**The George Floyd Effect: How Protests and Public Scrutiny Change Police Behavior (with Chris Casella, Derek Epp, Klara Fredriksson, and Hannah Walker)** *Perspectives on Politics* (2025) [[PDF]](pdfs/pubs/gf_fin.pdf) [[Replication]](https://doi.org/10.7910/DVN/KKFQAH)

**Fickle Prosociality: How Exposure to Violence Against LGBTQ+ People Motivates Mass Prosocial Responses Toward LGBTQ+ Group Members (with Jack Thompson)** *American Political Science Review* (2024) [[PDF]](pdfs/pubs/pulseapsr.pdf) [[Replication]](https://doi.org/10.7910/DVN/PA2XXO)

**Consent Searches: Evaluating the Usefulness of a Common and Highly Discretionary Police Practice (with Megan Dias, Derek Epp, and Hannah Walker)** the *Journal of Empirical Legal Studies* (2024) [[PDF]](pdfs/pubs/consentfinal.pdf)

**The Wages of Latinidad: How Immigration Enforcement Mitigates Anti-Black Assimilation (with Crystal Robertson)** *Political Behavior* (2024) [[PDF]](pdfs/pubs/wages.pdf) [[Replication]](https://doi.org/10.7910/DVN/WG1QRH)

**Living in the Shadow of Deportation: How Immigration Enforcement Forestalls Political Assimilation ** *Political Research Quarterly* (2023) [[PDF]](pdfs/pubs/depthreat1.pdf) [[Replication]](https://www.dropbox.com/s/j362qehlr3p2an6/replication_prq.zip?dl=0)

**How Social Ties with Undocumented Immigrants Motivate Latinx Political Participation (first author, with Hannah Walker and Matt Barreto)** *Political Research Quarterly* (2022) [[PDF]](pdfs/pubs/prq_cacc.pdf) [[Replication]](https://www.dropbox.com/s/ywh8fwa9ms02nnc/replication_folder.zip?dl=0)

**The Ripple Effect: The Political Consequences of Proximal Contact with Immigration Enforcement (with Matt Barreto and Hannah Walker)** the *Journal of Race, Ethnicity, and Politics* (2020) [[PDF]](pdfs/pubs/ripple_effect.pdf)

**The Direct and Indirect Effects of Immigration Enforcement on Latino Political Engagement (with Matt Barreto and Hannah Walker)** *UCLA Law Review* (2019) [[PDF]](pdfs/pubs/enforcement_engagement.pdf)
<br> <br> 

## Working Papers

**In the Shadow of Deportation: How Immigration Enforcement Shapes The Politics of Latinx Communities (Book Project)**

**Deporter-in-Chief or Champion-in-Chief? How the Threat of Immigration Enforcement Shapes Latinx Presidential Politician Evaluations (with Angela Gutierrez)**  [[PDF]](pdfs/wps/threatprefs3.pdf)

**The X Factor: How Group Labels Shape Politics (with Amanda D'Urso)**  [[PDF]](pdfs/wps/latinx_project.pdf)

<ul>
  <li>Featured on the [Washington Post](https://www.washingtonpost.com/opinions/2024/11/01/latinx-latinos-trump-democrats/), [Newsweek](https://www.newsweek.com/latinx-latino-voters-donald-trump-1977268), the [Financial Times](https://www.ft.com/content/73a1836d-0faa-4c84-b973-554e2ca3a227), the [Latin Times](https://www.latintimes.com/use-term-latinx-democratic-politicians-costing-them-votes-new-study-claims-564359), [LGBTQ Nation](https://www.lgbtqnation.com/2024/10/latino-voters-are-more-likely-to-oppose-politicians-who-use-the-term-latinx/), and the [Commonwealth Beacon](https://commonwealthbeacon.org/politics/study-finds-use-of-gender-neutral-latinx-by-democratic-pols-is-costing-them-votes/) </li>
</ul>


**The Immigration-to-Reproduction Shift: Latino Population Growth and White Support for Legal Abortion (with Benjamin Newman and Tyler Reny)** [[PDF]](pdfs/wps/abortion.pdf)

**Racialized Mass Shootings and Attitudes Toward Targeted Groups (with Kiela Crabtree)** [[PDF]](pdfs/wps/rviolence.pdf)

**How Police Respond to Increased Immigration Enforcement (with David Hausman)** [[PDF]](pdfs/wps/immigration_policing.pdf)

**Does Diversity Undermine Support for Redistribution? (with Marco Avina)** [[PDF]](pdfs/wps/redistribution.pdf)

**The Partisan-Ideological Sorting of New American Citizens (with Marco Avina)** [[PDF]](pdfs/wps/citsorting.pdf)

**The Role of Migration Motive in Immigrant Political Incorporation (with Roberto Carlos and Mashail Malik)** 

**Latinos in the House? Demographic Change, Ethnic Attrition, and Latino Political Behavior (with Alexander Agadjanian and Alejandro Flores)**[[PDF]](pdfs/wps/ethnic_attrition.pdf) 

**How Social Ties with Undocumented Immigrants Inform Latinx Identity Formation (with Ana Oaxaca and Rodolfo Solis)**